### ISSUE TITLE
Getting permission denied when trying to push a branch to make a PR

### ISSUE THREAD

**Issue by stclairdaniel** [swarajban/npm-cache#105]
I'd like to update the lodash version to remove a prototype pollution vulnerability, but I'm getting
`remote: Permission to swarajban/npm-cache.git denied to stclairdaniel.
fatal: unable to access 'https://github.com/swarajban/npm-cache.git/': The requested URL returned error: 403`

**Comment by tannerRP** [comment]
you need to fork the repository, push the branch to your own repo, and then make the PR from your repo/branch to this repo/develop

**Comment by stclairdaniel** [comment]
Thank you - I knew I must have been doing something wrong.
