### ISSUE TITLE
Command to check if there is a cache-hit (feature request)

### ISSUE THREAD

**Issue by cgmartin** [swarajban/npm-cache#13]
Sometimes it is helpful to know if the install will occur from cache or not, for conditional processing.

Something like: `npm-cache iscached npm` that returns an error status code upon cache-miss, or the hash string if the cache exists.

**Comment by minichate** [comment]
Does https://github.com/swarajban/npm-cache/pull/32 support that use case? If the item isn't in cache it will return no output; otherwise it'll return the hash

**Comment by cgmartin** [comment]
@minichate that should support it - users can test if output is an empty string upon cache-miss. Thanks! Closing this

**Comment by GMouron** [comment]
Would it be possible to re-open this issue ?

`npm-cache hash npm` appears to always return a value, whether the item is in cache or not.

Was there a change in the source code in the mean time ?

Thanks
