### ISSUE TITLE
Jspm support

### ISSUE THREAD

**Issue by Munter** [swarajban/npm-cache#20]
jspm is yet another package manager coming to frontend repositories. It would be great to also have support for caching those files.

The folder to be cached can be extrapolated from `require('package.json').jspm.directories.packages` with a fallback to `require('package.json').jspm.directories.baseURL` with a fallback to `./jspm_packages`

**Comment by swarajban** [comment]
New tools everyday in the JS world! Will work on this in the future

**Comment by sod** [comment]
Opended the PR https://github.com/swarajban/npm-cache/pull/39

**Comment by AStoker** [comment]
JSPM support would be fantastic

**Comment by swarajban** [comment]
Thanks for the pr, will likely get this merged in this week

**Comment by swarajban** [comment]
@Munter @AStoker : thanks to @sod 's #48, the latest release of npm-cache, 0.6.0, now has jspm support
