### ISSUE TITLE
Use composer.lock instead of composer.json

### ISSUE THREAD

**Issue by pelletiermaxime** [swarajban/npm-cache#21]
Hi, I just noticed this package is using the md5 of composer.json to see if there's any changes. This seems really wrong to me. Every project should commit his composer.lock and that file should be used, not the json.

**Comment by franzliedke** [comment]
:+1:

**Comment by swarajban** [comment]
@pelletiermaxime agreed, will address in upcoming relase

**Comment by swarajban** [comment]
Fixed in latest release, thanks for the PR @EHER
