### ISSUE TITLE
Pull Requests against `master` or `develop`?

### ISSUE THREAD

**Issue by nwinkler** [swarajban/npm-cache#25]
Which branch should I create pull requests against? It looks like `develop` is work in progress (portable `tar` etc.) - which one should I use for a PR fixing some inconsistencies?

**Comment by swarajban** [comment]
Sorry for the confusion. Please make the PR against `feature/pull-requests`. `develop` is in-progress and is not stable at the moment. `feature/pull-requests` is the same as `master`, so please make the PR there.

**Comment by nwinkler** [comment]
OK, will do...
