### ISSUE TITLE
Not working when called as a root for installing bower dependencies

### ISSUE THREAD

**Issue by ntrifunovic** [swarajban/npm-cache#3]
[npm-cache] [ERROR] [bower] error running bower install
    [npm-cache] [ERROR] error installing dependencies

**Comment by swarajban** [comment]
Hm haven't seen that locally. What version of bower do you have? Can you paste your `bower.json`? Also, what was the exact command you ran?

**Comment by ntrifunovic** [comment]
The command I ran was:

    npm-cache install

The behavior I experienced was expected from Bower because I ran `npm-cache install` as a root user
which executed the following command: https://github.com/swarajban/npm-cache/blob/master/cacheDependencyManagers/bowerConfig.js#L26 (I needed to run this command as a root in my case - inside docker container. To fix this issue I modified the command to `bower install --allow-root`.)

See: http://bower.io/docs/api/#allow-root

**Suggestion**: add `installAsRootCommand` into `bowerConfig` and modify `npm-cache` tool so that it  uses different commands if the current user is a root user.

**Comment by swarajban** [comment]
Thanks for the note. I am currently working on a new release allowing you to specify custom flags  to each of the package managers. You could use this to pass the `--allow-root` flag to power. I'll post and update when it's live

**Comment by swarajban** [comment]
I just published a new release with the ability to specify custom options. Please check it out, and see if it works for you
