### ISSUE TITLE
Hide progress bar on npm install

### ISSUE THREAD

**Issue by orf** [swarajban/npm-cache#36]
[Word on the street is that the NPM progress bar is slow](https://github.com/npm/npm/issues/11283). As far as I can tell it's not explicitly disabled by this library, and seeing as the progress is hidden perhaps the `--progress=false` flag should be passed by default?

**Comment by swarajban** [comment]
Fixed in [npm 3.70](https://github.com/npm/npm/releases/tag/v3.7.0)

**Comment by orf** [comment]
The performance issue has been fixed, but isn't my suggestion valid
nonetheless? We don't display the progress, so why not explicitly disable
it?
