### ISSUE TITLE
npm run <script> does not work as intended

### ISSUE THREAD

**Issue by bluejamesbond** [swarajban/npm-cache#37]
`npm run <script>` where any `<script>` that refers to the `node_modules/.bin` generally has problems. e.g. mocha and grunt which maybe installed in the the relative `node_modules` folder

**Comment by hax** [comment]
duplicated as #33

**Comment by swarajban** [comment]
Is this fixed?

**Comment by swarajban** [comment]
Looks like this was fixed in #34. Please re-open if it isn't
