### ISSUE TITLE
npm-cache install for npm packages only

### ISSUE THREAD

**Issue by cblair** [swarajban/npm-cache#38]
Is there a way to do this? I'm getting bower errors, and its pretty time consuming to set them up for my cluster slave nodes. Just need to install npm stuff, so is there a way to skip bower?

**Comment by swarajban** [comment]
Try `npm-cache install bower`

**Comment by swarajban** [comment]
Ah my bad, I mean `npm-cache install npm`

**Comment by cblair** [comment]
Worked perfect! Using command line options, had to use it like:

`npm-cache --cacheDirectory ./npm_cache install npm`

**Comment by cblair** [comment]
Whoops, I meant `npm-cache install --cacheDirectory ./npm_cache npm`.

Thanks!
