### ISSUE TITLE
Add option to store dependencies compressed

### ISSUE THREAD

**Issue by klausbayrhammer** [swarajban/npm-cache#49]
Hi,

I stumbled upon npm-cache yesterday and I totally loved the idea. Then I made a few tests with showed quite promising results (`npm i` took 5,7 mins `npm-cache install npm` 3,43). After further investigation I found out that the slowest part of `npm-cache install npm` is extracting the archive (obviously) and I wondered if we could add a switch to store the dependencies without compressing them. Because in our case the compressed tar-file has 219MB and the uncompressed node_modules directory has 246MB (and normally disk space is not the problem in a CI-environment) and just resolving the hash and copying a directory should be blazingly fast.

We could probably do something like `npm-cache install --deflate` in order to just copy the node_modules to the cacheDirectory without compressing them. And for resolving the dependencies we could scan the cacheDirectory for either #{HASH}.tar.gz files or directories with the specified hash.

What do you think about that idea? If you like it as well I'd be happy to contribute a PR.

**Comment by swarajban** [comment]
Ah that's great! I can't believe I never considered not gzipping... Would happily accept a PR with at command-line flag like `--deflate`. We just need to be careful to not break people's existing cached dependencies.

**Comment by avdv** [comment]
Hi.

I was just wondering, maybe I'm missing something, but for me the tar files are _not_ compressed:

```
file .package_cache/npm/2.14.13/df3d20831519057c0d76203d9b392638.tar.gz
.package_cache/npm/2.14.13/df3d20831519057c0d76203d9b392638.tar.gz: POSIX tar archive
```

Extracting a tar archive should be quite fast already:

```
time tar xf ~/.package_cache/npm/2.14.13/df3d20831519057c0d76203d9b392638.tar.gz
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

real	0m6.021s
user	0m0.365s
sys	0m2.019s
```

(yes, npm-cache created an invalid tar archive of my dependencies without even noticing, there was no error when running `npm-cache install`)

Comparing to `cp` there's not a big difference:

```
time cp -a copy/node_modules/ .

real	0m4.190s
user	0m0.496s
sys	0m3.424s
```

So, it is solely the npm tar module which is so slow (and probably buggy):

```
time node extract.js 
An error occurred: { [Error: unexpected eof]
  code: undefined,
  path: undefined,
  fstream_type: undefined,
  fstream_path: undefined,
  fstream_class: 'Extract',
  fstream_stack: 
   [ 'Extract._streamEnd (/tmp/tarred/node_modules/tar/lib/extract.js:91:35)',
     'BlockStream.<anonymous> (/tmp/tarred/node_modules/tar/lib/parse.js:51:8)',
     'BlockStream.emit (events.js:104:17)',
     'BlockStream._emitChunk (/tmp/tarred/node_modules/tar/node_modules/block-stream/block-stream.js:203:10)',
     'BlockStream.resume (/tmp/tarred/node_modules/tar/node_modules/block-stream/block-stream.js:58:15)',
     'Extract.Reader.resume (/tmp/tarred/node_modules/tar/node_modules/fstream/lib/reader.js:249:34)',
     'Entry.<anonymous> (/tmp/tarred/node_modules/tar/lib/parse.js:261:8)',
     'Entry.emit (events.js:104:17)' ] }

real	1m31.949s
user	1m17.760s
sys	0m20.888s
```

**Comment by klausbayrhammer** [comment]
@avdv good catch it really looks like that. We should look into that.

Nevertheless I think it would be cool to have a `--deflate` option because we could probably follow it up with a `--symlink` option where we don't copy the node_modules if there is a deflated cached version but just create a symlink.

**Comment by avdv** [comment]
Well, perhaps call it `--no-archive` to match the effect it has. It doesn't deflate anything, because it doesn't compress anything to begin with :wink:

I'm just going to use a Bash script for this, with `cp --reflink=auto` (btrfs). Works like a charm:

```bash
declare package_md5=$(md5sum -b package.json | cut -d' ' -f1)

if [[ ! -d $HOME/.cache/npm_packages/$package_md5 ]]; then
  npm_config_spin=false npm install --no-optional | tee npm-install.log
 
  mkdir -p "$HOME/.cache/npm_packages"
  cp -aT node_modules "$HOME/.cache/npm_packages/$package_md5"
else
  cp --reflink=auto -rT "$HOME/.cache/npm_packages/$package_md5" node_modules
fi
```

(Using symlinks did not work, because node could not find some packages)

**Comment by JoshSchreuder** [comment]
Great idea, decompressing takes most of the time and we're not super worried about disk space on the CI server. :+1: for this!

**Comment by klausbayrhammer** [comment]
Thanks for the feedback @JoshSchreuder @avdv. I've renamed to option to `noArchive` (camelcase) to be consistent with the other options (`forceRefresh`, `cacheDirectory`)

**Comment by hemdada** [comment]
We also need this feature. When can we expect to be merged?

**Comment by klausbayrhammer** [comment]
Sorry for the delay - I'm going to rebase it either today or tomorrow

**Comment by kemenaran** [comment]
@klausbayrhammer the feature looks awesome, and would definitely help us on our own CI!

**Comment by lunetics** [comment]
@klausbayrhammer any update on this?

**Comment by hax** [comment]
any update?

**Comment by adouglas** [comment]
+1 on getting this in asap

**Comment by hax** [comment]
I'm tired to wait and wait 💤  and I start a new project https://github.com/hax/dependencaches to replace npm-cache 😎

**Comment by swarajban** [comment]
Finally added in latest release thanks to a PR. Just add `--noArchive`
