### ISSUE TITLE
'npm link'd repository handling

### ISSUE THREAD

**Issue by dandehavilland** [swarajban/npm-cache#5]
If I link a local directory as a dependency to my project (i.e. `npm link my-local-package`), that dependency is then represented as a symlink in the `node_modules` directory. If I now run `npm-cache install`, and I had previously used a different version of that local package, it will unpack the cached version into the symlinked directory, overwriting whatever is currently there.

To avoid this, I would suggest that `npm-cache install` removes any linked packages/symlinked directories before unpacking the cache.

**Comment by swarajban** [comment]
Ah interesting. Thanks for the tip. Looks like there are a couple outstanding issues right now. I'll address this one in the next release. Hoping for the end of the week

**Comment by swarajban** [comment]
Just `rm -rf`'d the directory before extracting dependencies. Let me know if this works for you
