### ISSUE TITLE
tar-fs vs node-tar

### ISSUE THREAD

**Issue by JonWallsten** [swarajban/npm-cache#53]
I read another issue about performance. Ran across this test: 
https://gist.github.com/mafintosh/8102201

Is it possible to use tar-fs instead of node-tar if this test is really correct, and I'm not misunderstanding anything.

**Comment by JonWallsten** [comment]
After a quick test with just the writing part i had 1m51s for tar-fs and 2.25 seconds for node-tar. But the uncompressed option might make this obsolete. https://github.com/swarajban/npm-cache/pull/50

**Comment by JoshSchreuder** [comment]
So I ran a few trials (Windows 8, Node v5.7.0):

| | Attempt 1 | Attempt 2 | Attempt 3 | Average |
| ---------------- | ------------- | ------------- | ------------- | ------------- |
| **0.6.0 Clean** | 45.02s  | 40.62s  | 47.49s | 44.37s |
| **0.6.0 Cached**  | 26.20s  | 24.69s | 25.62s | 25.50s |
| | | | 
| **no-archive Clean**  | 43.20s  | 41.43s | 49.37s | 44.66s |
| **no-archive Cached**  | 17.57s  | 17.83s | 15.66s | 17.02s |
| | | |
| **tar-fs Clean**  | 39.01s  | 43.09s | 42.65s | 41.58s |
| **tar-fs Cached**  | 16.82s  | 15.73s | 15.17s | 15.90s |

The one thing I didn't cater for was network latency, so the clean runs may have some margin of error to them. You could eliminate this by running a network cache, but I couldn't be bothered :smile: I expect the cached runs are accurate.

It looks like there is significant improvement to be made by eliminating or improving unarchiving. `tar-fs` performed better than the stock `node-tar` in this regard.

**Comment by JonWallsten** [comment]
Nice work! Let wait to se that the creator says about this! :)

**Comment by lunetics** [comment]
any updates on this?

**Comment by swarajban** [comment]
Fixed in latest release :)
