### ISSUE TITLE
npm-cache shuold respect NODE_ENV or --production

### ISSUE THREAD

**Issue by skhavari** [swarajban/npm-cache#63]
its pretty common to have `dependencies` and `devDependencies` in `package.json` and use `NODE_ENV=production` or `npm install --production` to omit `devDependencies`.  Would be great if `npm-cache` would consider `NODE_ENV` and/or have a `--production` flag and work the same way.

**Comment by swarajban** [comment]
Ah good idea. I haven't had time to go through these, but happy to accept a PR

**Comment by swarajban** [comment]
You can specify this behavior with `npm-cache install npm --production`
