### ISSUE TITLE
Got "EXDEV, cross-device link not permitted" after upgrade to 0.6.1

### ISSUE THREAD

**Issue by hax** [swarajban/npm-cache#64]
It seems related to #58 .

**Comment by swarajban** [comment]
What node version + OS?

**Comment by hax** [comment]
Node v4 + Cent OS 6

I don't have enough time to find the real reason, but at least if tmp and cache dir are in different device, it may fail like this. (Though in my case, tmp and cache are in same device, so need more time to debug...)

**Comment by hax** [comment]
I guess https://github.com/swarajban/npm-cache/pull/58/files#r61316687 may fix the problem.

**Comment by hax** [comment]
Update: I have confirmed that our case is the tmp directory is on a memory-based fs, not same device as npm cache dir. It's a common use case.  

 Currently we fallback to 0.6.0.

It's easy to fix as my last code comment, so I not create a separate PR. Waiting for the new release.

**Comment by swarajban** [comment]
Released under `0.6.2` Let me know if that fixes your issue

**Comment by hax** [comment]
Thank you! We will test it next monday 😄

**Comment by zhujunsan** [comment]
Confirmed fix
