### ISSUE TITLE
How to install specific NPM packages with global flag?

### ISSUE THREAD

**Issue by IAMtheIAM** [swarajban/npm-cache#67]
Hello. I want to execute this 
`npm install -g typings webpack-dev-server rimraf webpack`

What is the proper syntax to tell npm-cache to execute npm install on specific pacakges only, and globally?

I don't see the option to specify which npm package I want npm-cache to install, nor the option to pass global. Does it support this?

**Comment by swarajban** [comment]
ah good point, npm-cache, doesn't currently support installing 'new' packages locally, it is only meant for installing packages from your package.json. Given its primary use case in build pipelines, I don't think this is worth adding at the moment.
