### ISSUE TITLE
install npm --production gives same result as without --production

### ISSUE THREAD

**Issue by fMads** [swarajban/npm-cache#74]
When running
npm-cache install npm --production
if you later run without --production on same package.json-file you get the same result

Ex
have a package.json file with devDependencies
run: npm-cache install npm --production
delete node_modules folder
run: npm-cache install npm
then node_modules doesn't container devDependencies

**Comment by rhys-eventbase** [comment]
I have noticed this also. I thought it was resolved in https://github.com/swarajban/npm-cache/issues/63 but it still appears to install dev dependencies regardless of argument or not

**Comment by sod** [comment]
I guess you cachefile already exists and was created without `--production`

one forceRefresh will redo the cache

```bash
npm-cache install --forceRefresh npm --production
```

Maybe the command with arguments should be part of the cache hash.

**Comment by swarajban** [comment]
+1 to @sod . If someone wants to fix up the PR in #78, that might be the best option
