### ISSUE TITLE
add support for passing registry flag to npm

### ISSUE THREAD

**Issue by klh** [swarajban/npm-cache#89]
changing registry is useful for instance when using npm_lazy or other proxies
typically used like so:

```
npm --registry http://localhost:8080/ install 
```

would be useful to use in combination with npm_lazy

just pass alla   args not caught by npm-cache onwards to npm other types are:

```
npm install --production
```

so in that case

```
npm-cache install --production 
```
should be viable

**Comment by sod** [comment]
that already works, just write `npm-cache install npm --production`, all options after the keyword `npm` are passed forward.

**Comment by swarajban** [comment]
^^ closing this
