### ISSUE TITLE
Support for multiple verions of node

### ISSUE THREAD

**Issue by brentjohnson** [swarajban/npm-cache#9]
Some node modules have a binary compilation piece to the (phantomjs for example) which results in an "npm install" that is only compatible with the verion of node that compiled it.  So if I try to build the same project with two different versions of node, the second one gets an error because it pulls in the node_modules of the first one.

I could manually script different --cacheDirectory locations for each node version, but it would be nice if the tool did that.  Maybe under the --cacheDirectory should be a directory for the node version used to create it, then the md5sum.  For example:

~/.package_cache/0.10.32/8a944a089acdeeafbf831f58d2813c85.tar.gz
~/.package_cache/0.12.4/8a944a089acdeeafbf831f58d2813c85.tar.gz

**Comment by swarajban** [comment]
Ah you're right, that's a good find. It should definitely do something like your proposal. I apologize for not keeping up with these issues; been busy at work :(

**Comment by swarajban** [comment]
Thanks for the suggestion, I've implemented this in the latest release: https://github.com/swarajban/npm-cache/releases/tag/0.3.3

The cache structure for node is now:
```
~/.package_cache/npm/2.9.1/<md5.tar.gz>
~/.package_cache/npm/1.4.28/<md5.tar.gz>
```

Hopefully this fixes your issue
